# Generated by Django 4.0.4 on 2022-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibraryAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='playlists',
            field=models.ManyToManyField(related_name='albums', through='musiclibraryAPI.PlaylistAlbum', to='musiclibraryAPI.playlist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=40),
        ),
    ]
